apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio-operator
commonAnnotations:
  operator.min.io/authors: "MinIO, Inc."
  operator.min.io/license: "AGPLv3"
  operator.min.io/support: "https://subnet.min.io"

resources:
  - resources/base/namespace.yaml
  - resources/base/service-account.yaml
  - resources/base/cluster-role.yaml
  - resources/base/cluster-role-binding.yaml
  - resources/base/crds/minio.min.io_tenants.yaml
  - resources/base/service.yaml
  - resources/base/deployment.yaml
  - resources/base/console-ui.yaml


