apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Configure repo and tag of MinIO Operator Image
images:
  - name: minio/operator
    newName: minio/operator
    newTag: v4.0.0

namespace: minio-operator

resources:
  - operator-kustomize/namespace.yaml
  - operator-kustomize/service-account.yaml
  - operator-kustomize/cluster-role.yaml
  - operator-kustomize/cluster-role-binding.yaml
  - operator-kustomize/base/crds/minio.min.io_tenants.yaml
  - operator-kustomize/service.yaml
  - operator-kustomize/deployment.yaml
  - operator-kustomize/console-ui.yaml
