{{ $namespace := .Release.Namespace }}
{{ range .Values.tenants }}
{{- if .console.secrets.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .console.secrets.name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  ## Passphrase to encrypt jwt payload
  CONSOLE_PBKDF_PASSPHRASE: {{ .console.secrets.passphrase | b64enc }}
  ## Salt to encrypt jwt payload
  CONSOLE_PBKDF_SALT: {{ .console.secrets.salt | b64enc }}
  ## MinIO User Access Key (used for Console Login)
  CONSOLE_ACCESS_KEY: {{ .console.secrets.accessKey | b64enc }}
  ## MinIO User Secret Key (used for Console Login)
  CONSOLE_SECRET_KEY: {{ .console.secrets.secretKey | b64enc}}
{{- end }}
{{ end }}
