apiVersion: v1
kind: Service
metadata:
  name: "operator"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minio-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 4222
      name: http
    - port: 4233
      name: https
  selector:
    {{- include "minio-operator.selectorLabels" . | nindent 4 }}
