{{ range .Values.tenants }}
---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  ## Optionally pass labels to be applied to the statefulset pods
  labels:
    app: minio
  {{ if dig "metrics" "enabled" false . }}
  ## Annotations for MinIO Tenant Pods
  annotations:
    prometheus.io/path: /minio/v2/metrics/cluster
    prometheus.io/port: {{ dig "metrics" "port" 9000 . | quote }}
    prometheus.io/scrape: "true"
  {{ end }}
  {{ if dig "scheduler" "name" "" . }}
  scheduler:
    name: {{ dig "scheduler" "name" "" . }}
  {{ end }}
spec:
  image: {{ dig "image" "repository" "minio/minio" . }}:{{ dig "image" "tag" "RELEASE.2021-10-06T23-36-31Z" . }}
  imagePullPolicy: {{ dig "image" "pullPolicy" "IfNotPresent" . }}
  {{ if dig "imagePullSecret" "name" "" . }}
  imagePullSecret:
    name: {{ dig "imagePullSecret" "name" "" . }}
  {{ end }}
  ## Secret with credentials to be used by MinIO Tenant.
  {{ if dig "secrets" "enabled" false . }}
  credsSecret:
    name: {{ dig "secrets" "name" "" . }}
  {{ end }}
  {{ range (dig "pools" (list) .) }}
  pools:
    - servers: {{ dig "servers" 4 . }}
      volumesPerServer: {{ dig "volumesPerServer" 4 . }}
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          storageClassName: {{ dig "storageClassName" "" . }}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ dig "size" "10Gi" . }}
      {{- with (dig "tolerations" (list) .) }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{- with (dig "nodeSelector" (dict) .) }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{- with (dig "affinity" (dict) .) }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{- with (dig "resources" (dict) .) }}
      resources:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{- with (dig "securityContext" (dict) .) }}
      securityContext:
        {{ toYaml . | nindent 8 }}
      {{ end }}
      {{- with (dig "topologySpreadConstraints" (list) .) }}
      topologySpreadConstraints:
        {{ toYaml . | nindent 8 }}
      {{ end }}
  {{ end }}
  mountPath: {{ dig "mountPath" "/export" . }}
  subPath: {{ dig "subPath" "/data" . }}
  {{- with (dig "certificate" "externalCaCertSecret" (dict) .) }}
  externalCaCertSecret:
    {{ toYaml . | nindent 6 }}
  {{ end }}
  {{- with (dig "certificate" "externalCertSecret" (dict) .) }}
  externalCertSecret:
    {{ toYaml . | nindent 6 }}
  {{ end }}
  requestAutoCert: {{ dig "certificate" "requestAutoCert" false . }}
  s3:
    bucketDNS: {{ dig "s3" "bucketDNS" false . }}
  {{- with (dig "certificate" "certConfig" (dict) .) }}
  certConfig:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  podManagementPolicy: {{ dig "podManagementPolicy" "Parallel" . }}
  {{- with (dig "serviceMetadata" (dict) .) }}
  serviceMetadata:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with (dig "env" (dict) .) }}
  env:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  {{ if dig "priorityClassName" "" . }}
  priorityClassName: {{ dig "priorityClassName" "" . }}
  {{ end }}
{{ end }}
