apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tenant-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: 5t
spec:
  tls:
    - hosts:
        - minio.example.com
        - console.example.com
      secretName: tenant-tls
  rules:
    - host: minio.example.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: minio
                port:
                  number: 80
    - host: console.example.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: myminio-console
                port:
                  number: 9090