apiVersion: v1
kind: Service
metadata:
  name: operator # Please do not change this value
  labels:
    name: minio-operator
  namespace: minio-operator
spec:
  type: ClusterIP
  ports:
    - port: 4222
      name: http
    - port: 4233
      name: https
  selector:
    name: minio-operator
