apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tenant-psp

resources:
  - auditlog-sa.yaml
  - prometheus-sa.yaml
  - minio-sa.yaml
  - ../base

patchesStrategicMerge:
  - tenant.yaml