apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: console-sa
    operator.min.io/authors: MinIO, Inc.
    operator.min.io/license: AGPLv3
    operator.min.io/support: https://subnet.min.io
    operator.min.io/version: v5.0.15
  name: console-sa-secret
type: kubernetes.io/service-account-token
