{{- if .Values.console.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "minio-operator.console-fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.console.ingress.labels }}
  labels: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.console.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.console.ingress.ingressClassName }}
  ingressClassName: {{ .Values.console.ingress.ingressClassName }}
  {{- end }}
  {{- if .Values.console.ingress.tls }}
  tls:
    {{- range .Values.console.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.console.ingress.host }}
      http:
        paths:
          - path: {{ .Values.console.ingress.path }}
            pathType: {{ .Values.console.ingress.pathType }}
            backend:
              service:
                name: "console"
                port:
                  name: http
{{ end }}
