apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: minio-operator-binding
  labels: {{- include "minio-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: minio-operator-role
subjects:
  - kind: ServiceAccount
    name: minio-operator
    namespace: {{ .Release.Namespace }}
