apiVersion: v1
kind: Service
metadata:
  name: operator
  namespace: {{ .Release.Namespace }}
  labels: {{- include "minio-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 4221
      name: http
  selector:
    operator: leader
    {{- include "minio-operator.selectorLabels" . | nindent 4 }}
