apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: storage
  namespace: minio-tenant
spec:
  ## Add environment variables to be set in MinIO container (https://github.com/minio/minio/tree/master/docs/config)
  env:
    - name: MINIO_IDENTITY_OPENID_CONFIG_URL
      value: "https://your-extenal-idp.com/.well-known/openid-configuration" # Your external identity provide configuration
    - name: MINIO_IDENTITY_OPENID_CLIENT_ID
      value: "OPENID CLIENT ID"
    - name: MINIO_IDENTITY_OPENID_CLIENT_SECRET
      value: "OPENID CLIENT SECRET"
    - name: MINIO_IDENTITY_OPENID_SCOPES
      value: "openid,profile,email"
    - name: MINIO_IDENTITY_OPENID_CLAIM_NAME
      value: "https://min.io/policy"
