apiVersion: v1
data:
  CONSOLE_PORT: "9090"
  CONSOLE_TLS_PORT: "9443"
kind: ConfigMap
metadata:
  annotations:
    operator.min.io/authors: MinIO, Inc.
    operator.min.io/license: AGPLv3
    operator.min.io/support: https://subnet.min.io
    operator.min.io/version: v5.0.15
  labels:
    app.kubernetes.io/name: operator
  name: console-env
